name: Bump Number

on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test unity-mobile-build-number-bumper
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Unity Mobile Build Bumper
        uses: Breakstep-Studios/unity-mobile-build-number-bumper@v1