name: Bump Number

on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test unity-mobile-build-number-bumper
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: bundle-version-updates
      - name: Unity Mobile Build Bumper
        uses: Breakstep-Studios/unity-mobile-build-number-bumper@docker
      - name: "Add, Commit And Push Prepared Files"
        run: |
          git config --global user.email "releasebot@users.noreply.github.com"
          git config --local user.name "release bot"
          git checkout bundle-version-updates
          git add -A
          git commit -m "Updated bundle versions"
          git push